LANG = {
    "FR": {
        "title": "ForenSIM Extractor - V2.01",
        "tab_mission": "🔍 Extraction SIM",
        "tab_scanner": "🛠️ Scanner SmartCard",
        "tab_osint": "🔎 OSINT & Parsing",
        "tab_about": "ℹ️ À propos",
        "tab_clone": "📑 Clonage SIM",
        "tab_risk": "🛑 Actions Risquées",
        "lbl_clone_warning": "⚠️ Nécessite une carte SIM Vierge Programmable (ex: SysmoISIM) et sa Clé ADM.",
        "lbl_target_iccid": "ICCID Cible :",
        "lbl_target_imsi": "IMSI Cible :",
        "btn_import_last": "Importer depuis la dernière extraction",
        "lbl_adm_key": "Clé ADM (Hex) :",
        "btn_burn_clone": "▶ GRAVER LE CLONE",
        "lbl_pysim": "Dossier pySim :",
        "btn_browse": "Parcourir",
        "lbl_reader": "Choix du Lecteur :",
        "lbl_profile": "Profil Cible :",
        "sw_pin": "Déverrouiller avec PIN",
        "ent_pin_placeholder": "PIN",
        "btn_test_pin": "Valider PIN",
        "btn_null_verify": "Vérifier statut",
        "ent_puk_placeholder": "PUK",
        "ent_new_pin_placeholder": "Nouveau",
        "btn_unblock_puk": "Débloquer",
        "btn_change_pin": "Modifier",
        "btn_start": "▶ DÉMARRER L'EXTRACTION",
        "btn_stop": "🛑 STOP",
        "status_ready": "[*] Prêt pour la mission...\n",
        "lbl_sec_basic": "Sécurité & Analyse (Safe)",
        "lbl_current_pin": "Code PIN:",
        "lbl_sec_adv": "ZONE À RISQUE (Écriture)",
        "lbl_puk_unlock": "PUK:",
        "lbl_change_pin": "Changer:",
        # Scanner
        "btn_identify": "Identifier la carte présente",
        # Osint
        "btn_search": "Recherche OSINT",
        "ent_query_placeholder": "Entrez IMSI, ICCID ou MAC...",
        # About
        "about_desc": "Outil d'Investigation Numérique (Forensic) pour cartes UICC / eUICC.\nCréé pour automatiser la mise sous scellé (SHA-256) et l'extraction de preuves (Logical & File System).",
        "about_dev": "✒️ Développé et Audité par :",
        "about_links": "🔗 Ressources & Dépendances :",
        "about_explanations": "📌 EXPLICATIONS TECHNIQUES :\n\n- Le mode 'Gentle Poke' (Null Verify) permet d'interroger le statut de sécurité de la carte sans soumettre de code PIN. L'outil lit l'EF.LOCI (6F7E) d'abord et évalue le SW1 SW2 renvoyé, ce qui ne brûle aucun essai.\n- Le 'Live PIN Test' envoie une commande VERIFY CHV (0x20) pour valider officiellement le code PIN entré.\n- Le scellé (tar.gz) capture le flux exact de lecture binaire du FileSystem et génère un hash SHA-256 automatique.",
    },
    "EN": {
        "title": "ForenSIM Extractor - V2.01",
        "tab_mission": "🔍 SIM Extraction",
        "tab_scanner": "🛠️ SmartCard Scanner",
        "tab_osint": "🔎 OSINT & Parsing",
        "tab_about": "ℹ️ About",
        "tab_clone": "📑 SIM Cloning",
        "tab_risk": "🛑 Risky Actions",
        "lbl_clone_warning": "⚠️ Requires a Programmable Blank SIM Card (e.g. SysmoISIM) and its ADM Key.",
        "lbl_target_iccid": "Target ICCID:",
        "lbl_target_imsi": "Target IMSI:",
        "btn_import_last": "Import from last extraction",
        "lbl_adm_key": "ADM Key (Hex):",
        "btn_burn_clone": "▶ BURN CLONE",
        "lbl_pysim": "pySim Folder :",
        "btn_browse": "Browse",
        "lbl_reader": "Select Reader:",
        "lbl_profile": "Target Profile:",
        "sw_pin": "Unlock with PIN",
        "ent_pin_placeholder": "PIN",
        "btn_test_pin": "Validate PIN",
        "btn_null_verify": "Check Status",
        "ent_puk_placeholder": "PUK",
        "ent_new_pin_placeholder": "New",
        "btn_unblock_puk": "Unblock",
        "btn_change_pin": "Change",
        "btn_start": "▶ START EXTRACTION",
        "btn_stop": "🛑 STOP",
        "status_ready": "[*] Ready for mission...\n",
        "lbl_sec_basic": "Security & Analysis (Safe)",
        "lbl_current_pin": "PIN Code:",
        "lbl_sec_adv": "RISK ZONE (Writing)",
        "lbl_puk_unlock": "PUK:",
        "lbl_change_pin": "Change:",
        # Scanner
        "btn_identify": "Identify Card Present",
        # Osint
        "btn_search": "Search OSINT",
        "ent_query_placeholder": "Enter IMSI, ICCID or MAC...",
        # About
        "about_desc": "Digital Forensics Tool for UICC / eUICC cards.\nAutomated evidence extraction, parsing, and digital sealing (SHA-256).",
        "about_dev": "✒️ Developed and Audited by:",
        "about_links": "🔗 Resources & Dependencies:",
        "about_explanations": "📌 TECHNICAL EXPLANATIONS:\n\n- The 'Gentle Poke' (Null Verify) mode checks the security status without burning any PIN attempts. It does this by reading EF.LOCI (6F7E) and evaluating the SW1 SW2 APDU response.\n- The 'Live PIN Test' sends a VERIFY CHV (0x20) command to officially validate the entered PIN code.\n- The digital seal (tar.gz) captures the raw binary read flow of the FileSystem and generates an automatic SHA-256 hash.",
    }
}
